# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 31
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 170

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 4
Style/Documentation:
  Enabled: false

# Offense count: 5
#Style/RegexpLiteral:
#  MaxSlashes: 0
#
StringLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/BlockComments:
  Enabled: false

