FROM ruby:3.0.4

RUN apt-get update && apt-get install -y nodejs postgresql-client sqlite3 vim --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN adduser  app_user --home /app

WORKDIR /app
USER app_user

ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

COPY Gemfile /app/
COPY Gemfile.lock /app/
RUN bundle config --global frozen 1
RUN bundle config  set --local  path vendor/bundle
RUN bundle config  set  --local cache vendor/cache
RUN bundle install 

COPY . /app
#RUN bundle exec rake -T
#EXPOSE 3000
#CMD ['rails', 'server', '-b', '0.0.0.0']
